"""Trying to implement DayRecords

Revision ID: 0f41f195c1bd
Revises: 94a11dd898c6
Create Date: 2019-08-28 16:55:11.464933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f41f195c1bd'
down_revision = '94a11dd898c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_records',
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.drop_table('day records')
    op.create_foreign_key(None, 'goal instances', 'day_records', ['day_recorded_date'], ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goal instances', type_='foreignkey')
    op.create_table('day records',
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.drop_table('day_records')
    # ### end Alembic commands ###
