"""Updated Goal model with the target

Revision ID: 3d7a56fccd9d
Revises: 55904060dadc
Create Date: 2019-07-30 16:05:33.854665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7a56fccd9d'
down_revision = '55904060dadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('target', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'target')
    # ### end Alembic commands ###
