"""Creating DayRecords model

Revision ID: 94a11dd898c6
Revises: 400943e3abe7
Create Date: 2019-08-28 16:16:33.443422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a11dd898c6'
down_revision = '400943e3abe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day records',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day records')
    # ### end Alembic commands ###
