"""Created GoalInstance model

Revision ID: 97206428c6f7
Revises: 3d7a56fccd9d
Create Date: 2019-07-30 22:43:04.760871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97206428c6f7'
down_revision = '3d7a56fccd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances of a goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instances of a goal_timestamp'), 'instances of a goal', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instances of a goal_timestamp'), table_name='instances of a goal')
    op.drop_table('instances of a goal')
    # ### end Alembic commands ###
