"""Added target_type column to Goal model

Revision ID: b48d1d0b4450
Revises: e19910033713
Create Date: 2019-08-20 16:30:52.672656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48d1d0b4450'
down_revision = 'e19910033713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('target_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'target_type')
    # ### end Alembic commands ###
