"""Updated tablename for goal instances

Revision ID: e19910033713
Revises: 97206428c6f7
Create Date: 2019-08-13 10:12:27.225297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19910033713'
down_revision = '97206428c6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal instances_timestamp'), 'goal instances', ['timestamp'], unique=False)
    op.drop_index('ix_instances of a goal_timestamp', table_name='instances of a goal')
    op.drop_table('instances of a goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances of a goal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('goal_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instances of a goal_timestamp', 'instances of a goal', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_goal instances_timestamp'), table_name='goal instances')
    op.drop_table('goal instances')
    # ### end Alembic commands ###
